#!/usr/bin/env python3
"""Generate flight_radar/src/sprites/plane_24.{c,h}: a 24x24 LV_IMG_CF_ALPHA_8BIT
top-down airplane silhouette, nose pointing up (towards y = 0).

Pure Python, no Pillow. Rasterises polygons with 8x8 supersampling and an
even-odd point-in-polygon test; alpha = round(255 * inside / 64).
Usage: tools/gen_plane_sprite.py"""
import pathlib

W = H = 24
SUPERSAMPLE = 8

# Silhouette polygons in a 24x24 coordinate space (y = 0 is the nose / top).
POLYGONS = [
    # fuselage
    [(11, 1), (13, 1), (13.6, 6), (13.6, 18), (13, 22), (11, 22), (10.4, 18), (10.4, 6)],
    # wings
    [(10.6, 8), (13.4, 8), (23, 14.5), (23, 16.2), (13.4, 13.5), (10.6, 13.5), (1, 16.2), (1, 14.5)],
    # tailplane
    [(10.7, 18.5), (13.3, 18.5), (17.5, 21.6), (17.5, 22.8), (13.3, 21.4), (10.7, 21.4), (6.5, 22.8), (6.5, 21.6)],
    # fin
    [(11.6, 16), (12.4, 16), (12.4, 22.5), (11.6, 22.5)],
]


def point_in_polygon(x, y, poly):
    """Even-odd rule point-in-polygon test."""
    inside = False
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        if (y1 > y) != (y2 > y):
            x_at_y = x1 + (y - y1) * (x2 - x1) / (y2 - y1)
            if x < x_at_y:
                inside = not inside
    return inside


def point_in_any_polygon(x, y):
    for poly in POLYGONS:
        if point_in_polygon(x, y, poly):
            return True
    return False


def rasterize():
    pixels = [[0] * W for _ in range(H)]
    for j in range(H):
        for i in range(W):
            count = 0
            for sy in range(SUPERSAMPLE):
                for sx in range(SUPERSAMPLE):
                    x = i + (sx + 0.5) / SUPERSAMPLE
                    y = j + (sy + 0.5) / SUPERSAMPLE
                    if point_in_any_polygon(x, y):
                        count += 1
            pixels[j][i] = round(255 * count / 64)
    return pixels


def print_preview(pixels):
    for row in pixels:
        line = []
        for a in row:
            if a > 128:
                line.append("#")
            elif a > 32:
                line.append("+")
            else:
                line.append(".")
        print("".join(line))


def write_c(pixels, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    flat = [a for row in pixels for a in row]
    assert len(flat) == W * H

    c_path = out_dir / "plane_24.c"
    h_path = out_dir / "plane_24.h"

    with open(h_path, "w") as f:
        f.write(
            "// Generated by tools/gen_plane_sprite.py. Do not edit.\n"
            "#pragma once\n"
            "#include <lvgl.h>\n"
            "#ifdef __cplusplus\n"
            'extern "C" {\n'
            "#endif\n"
            "extern const lv_img_dsc_t plane_24;\n"
            "#ifdef __cplusplus\n"
            "}\n"
            "#endif\n"
        )

    with open(c_path, "w") as f:
        f.write("// Generated by tools/gen_plane_sprite.py. Do not edit.\n")
        f.write('#include "plane_24.h"\n\n')
        f.write("static const uint8_t plane_24_map[] = {\n")
        for j in range(H):
            row = flat[j * W:(j + 1) * W]
            f.write("  " + ", ".join(str(v) for v in row) + ",\n")
        f.write("};\n\n")
        f.write("const lv_img_dsc_t plane_24 = {\n")
        f.write("  .header = { .cf = LV_IMG_CF_ALPHA_8BIT, .always_zero = 0, .reserved = 0, .w = 24, .h = 24 },\n")
        f.write(f"  .data_size = {W * H},\n")
        f.write("  .data = plane_24_map,\n")
        f.write("};\n")

    print(f"wrote {c_path}")
    print(f"wrote {h_path}")


def main():
    pixels = rasterize()
    print_preview(pixels)
    out_dir = pathlib.Path(__file__).resolve().parent.parent / "flight_radar" / "src" / "sprites"
    write_c(pixels, out_dir)


if __name__ == "__main__":
    main()
