#!/usr/bin/env python3
"""Generate flight_radar/src/airports_data.cpp from OurAirports airports.csv.
Usage: tools/gen_airports.py [path-to-airports.csv]   (downloads if omitted)"""
import csv, io, sys, urllib.request, pathlib
URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
KEEP = {"large_airport": 1, "medium_airport": 0}
def load(path):
    if path: return open(path, newline="", encoding="utf-8").read()
    return urllib.request.urlopen(URL, timeout=60).read().decode("utf-8")
def main():
    text = load(sys.argv[1] if len(sys.argv) > 1 else None)
    rows = []
    for r in csv.DictReader(io.StringIO(text)):
        if r["type"] not in KEEP: continue
        ident = (r["icao_code"] or r["ident"])[:4].upper()
        if not ident or not ident.isalnum(): continue
        rows.append((float(r["latitude_deg"]), float(r["longitude_deg"]), ident, KEEP[r["type"]]))
    rows.sort()
    out = pathlib.Path(__file__).resolve().parent.parent / "flight_radar" / "src" / "airports_data.cpp"
    with open(out, "w") as f:
        f.write("// Generated by tools/gen_airports.py from OurAirports. Do not edit.\n#include \"airports.h\"\n")
        f.write("const Airport AIRPORTS[] = {\n")
        for lat, lon, ident, large in rows:
            f.write(f'  {{{lat:.5f}f, {lon:.5f}f, "{ident}", {large}}},\n')
        f.write("};\n")
        f.write(f"const size_t AIRPORTS_COUNT = {len(rows)};\n")
    print(f"wrote {len(rows)} airports to {out}")
if __name__ == "__main__": main()
