#!/usr/bin/env python3
"""gen_metadata_table.py: regenerate flight_radar/src/metadata_table.cpp from the
OpenSky aircraft metadata database, restricted to the Australian ICAO24 block
(0x7C0000-0x7FFFFF).

Usage:
    python3 tools/gen_metadata_table.py <csv path or URL>

The OpenSky CSV export is comma-delimited but quotes individual fields with a
single quote (') rather than a double quote, and only quotes fields that need
it (contain a comma, embedded quote, etc). We parse it with csv.reader using
quotechar="'" which handles that correctly, including the doubled '' escape
for a literal apostrophe inside a quoted field.
"""
import csv
import io
import os
import sys
import urllib.request

REG_WIDTH = 7      # char reg[8]  -> 7 chars + NUL
TYPE_WIDTH = 4      # char typecode[5] -> 4 chars + NUL
MODEL_WIDTH = 23    # char model[24] -> 23 chars + NUL
OP_WIDTH = 23       # char op[24] -> 23 chars + NUL

LO = 0x7C0000
HI = 0x7FFFFF

HEADER = """// metadata_table.cpp: GENERATED by tools/gen_metadata_table.py from the OpenSky
// aircraft metadata database. Do not edit by hand; rerun the generator instead.
// OpenSky-derived data under OpenSky's terms of use: keep it local, never
// commit it (CI only accepts the empty stub).
#include "metadata_table.h"
#include <cstdlib>

const MetadataRow METADATA[] = {
"""

FOOTER_TEMPLATE = """}};
const size_t METADATA_COUNT = {count};

const MetadataRow *metadataLookup(const char *icao24_hex) {{
  if (!icao24_hex || !icao24_hex[0]) return nullptr;
  char *end = nullptr;
  unsigned long key = std::strtoul(icao24_hex, &end, 16);
  if (!end || *end != '\\0' || key > 0xFFFFFFul) return nullptr;
  size_t lo = 0, hi = METADATA_COUNT;   // binary search over [lo, hi)
  while (lo < hi) {{
    size_t mid = lo + (hi - lo) / 2;
    uint32_t v = METADATA[mid].icao24;
    if (v == key) return &METADATA[mid];
    if (v < key) lo = mid + 1;
    else hi = mid;
  }}
  return nullptr;
}}
"""


def clean_ascii(value, width):
    """Strip whitespace, drop non-ASCII (replace with '?'), truncate to width,
    escape backslash and double-quote for embedding in a C string literal."""
    value = value.strip()
    out_chars = []
    for ch in value:
        if ord(ch) > 127:
            out_chars.append('?')
        else:
            out_chars.append(ch)
    value = ''.join(out_chars)[:width]
    value = value.replace('\\', '\\\\').replace('"', '\\"')
    return value


def open_csv_source(path_or_url):
    if path_or_url.startswith('http://') or path_or_url.startswith('https://'):
        req = urllib.request.Request(path_or_url, headers={'User-Agent': 'flight-radar-gen/1.0'})
        resp = urllib.request.urlopen(req, timeout=120)
        # Wrap the binary stream as text for the csv module.
        return io.TextIOWrapper(resp, encoding='utf-8', errors='replace', newline='')
    return open(path_or_url, newline='', encoding='utf-8', errors='replace')


def main():
    if len(sys.argv) != 2:
        print("usage: gen_metadata_table.py <csv path or URL>", file=sys.stderr)
        return 2

    src = sys.argv[1]
    rows = {}  # icao24 int -> (reg, typecode, model, op)

    f = open_csv_source(src)
    try:
        reader = csv.reader(f, quotechar="'")
        header = next(reader)
        idx = {name.strip().lower(): i for i, name in enumerate(header)}
        needed = ['icao24', 'registration', 'manufacturername', 'model', 'typecode', 'operator']
        for col in needed:
            if col not in idx:
                print(f"error: missing expected column '{col}' in CSV header: {header}", file=sys.stderr)
                return 1

        i_icao = idx['icao24']
        i_reg = idx['registration']
        i_manuf = idx['manufacturername']
        i_model = idx['model']
        i_type = idx['typecode']
        i_op = idx['operator']

        for row in reader:
            if len(row) <= max(i_icao, i_reg, i_manuf, i_model, i_type, i_op):
                continue
            icao_raw = row[i_icao].strip()
            if not icao_raw:
                continue
            try:
                icao_val = int(icao_raw, 16)
            except ValueError:
                continue
            if not (LO <= icao_val <= HI):
                continue
            if icao_val in rows:
                continue  # dedupe: keep the first occurrence

            reg = clean_ascii(row[i_reg], REG_WIDTH)
            if not reg:
                continue  # no registration: nothing useful to show on the card

            typecode = clean_ascii(row[i_type], TYPE_WIDTH)
            model = clean_ascii(row[i_model], MODEL_WIDTH)
            op = clean_ascii(row[i_op], OP_WIDTH)

            rows[icao_val] = (reg, typecode, model, op)
    finally:
        f.close()

    sorted_items = sorted(rows.items(), key=lambda kv: kv[0])

    out_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..',
        'flight_radar', 'src', 'metadata_table.cpp')
    out_path = os.path.normpath(out_path)

    with open(out_path, 'w', encoding='ascii') as out:
        out.write(HEADER)
        if sorted_items:
            lines = []
            for icao_val, (reg, typecode, model, op) in sorted_items:
                lines.append(
                    '  {0x%06x, "%s", "%s", "%s", "%s"}' % (icao_val, reg, typecode, model, op))
            out.write(',\n'.join(lines))
            out.write('\n')
        else:
            out.write('  {0, "", "", "", ""}\n')
        out.write(FOOTER_TEMPLATE.format(count=len(sorted_items)))

    print(f"wrote {len(sorted_items)} rows to {out_path}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
